export const data_myntra = [
    {
      "Platform": "Myntra",
      "breadcrumbs": "Home>Footwear>Men's Footwear>Casual Shoes>getVO Casual Shoes>Chelsea Boots For Men",
      "title": "getVO Chelsea Boots For Men",
      "price": 1000,
      "original_price": 2999,
      "discount %": 61,
      "currency": "MRP",
      "rating": "",
      "rating_count": "",
      "review_count": "",
      "offers": "5% Cashback on myntra Axis Bank Card,Sign up for myntra Pay Later and get myntra Gift Card worth up to ₹500*",
      "description": "",
      "highlights": "",
      "services": "Cash on Delivery,10 Days Return Policy",
      "seller": "GetvoIndia",
      "seller_rating": 4.4,
      "sizes": "6,7,8,9,10",
      "specifications": "",
      "images": "http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/9/m/m/8-sb5003-getvo-tan-original-imagjjfjrkhgmxk6.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/p/z/d/8-sb5003-getvo-tan-original-imagjjfjjja4yupv.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/r/j/e/8-sb5003-getvo-tan-original-imagjjfjxna6vxmb.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/x/c/u/8-sb5003-getvo-tan-original-imagjjfjgnqgshv4.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/y/d/i/8-sb5003-getvo-tan-original-imagjjfjjfmxnfen.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/h/z/0/8-sb5003-getvo-tan-original-imagjjfje2yh4ew7.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/t/w/p/8-sb5003-getvo-tan-original-imagjjfjukj4zhcm.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/j/a/h/8-sb5003-getvo-tan-original-imagjjfjregzphgc.jpeg",
      "detail_url": "https://www.myntra.com/getvo-chelsea-boots-men/p/itm7997ed4701612?pid=SHOGJJFP2UXDBTGP&lid=LSTSHOGJJFP2UXDBTGP57ML4F&marketplace=myntra&store=osp%2Fcil%2Fe1f"
    },
    {
      "Platform": "Myntra",
      "breadcrumbs": "Home>Clothing and Accessories>Topwear>T-shirts>Men's T-shirts>FTX Men's T-shirts>Pack of 4 Men Solid Round Neck Multicolor T-Shirt",
      "title": "FTX Solid Men Round Neck Multicolor T-Shirt",
      "price": 400,
      "original_price": 1499,
      "discount %": 65,
      "currency": "MRP",
      "rating": 4.1,
      "rating_count": 9185,
      "review_count": 769,
      "offers": "Deal Price ₹449,Sign up for myntra Pay Later and get myntra Gift Card worth up to ₹500*,5% Cashback on myntra Axis Bank Card",
      "description": "",
      "highlights": "",
      "services": "Cash on Delivery,10 Days Return Policy",
      "seller": "FORCAS APPARELS",
      "seller_rating": 4.7,
      "sizes": "S,M,L,XL",
      "specifications": "",
      "images": "http://rukmini1.flixcart.com/image/832/832/l2f20sw0/t-shirt/g/4/f/xl-723-5-2-7-8-xl-ftx-original-imagdrzxsvvdjnuk.jpeg,http://rukmini1.flixcart.com/image/832/832/l09w8sw0/t-shirt/o/a/i/m-tst-ab-36-54-ftx-original-imagc36nhgqatpfu.jpeg,http://rukmini1.flixcart.com/image/832/832/l09w8sw0/t-shirt/n/w/b/l-tst-ab-36-54-ftx-original-imagc36nu559bghj.jpeg,http://rukmini1.flixcart.com/image/832/832/l08gsy80/t-shirt/k/5/j/xl-tst-gy-ny-65-68-ftx-original-imagc2ua3nsfc2qh.jpeg,http://rukmini1.flixcart.com/image/832/832/l08gsy80/t-shirt/l/l/c/l-tst-gy-ny-65-68-ftx-original-imagc2uae2fjzrsc.jpeg,http://rukmini1.flixcart.com/image/832/832/l2f20sw0/t-shirt/d/n/a/l-723-2-7-4-8-l-ftx-original-imagdrzutdwnc3ph.jpeg",
      "detail_url": "https://www.myntra.com/ftx-solid-men-round-neck-multicolor-t-shirt/p/itmeafea80350b9b?pid=TSHGDSZFFZHARSGY&lid=LSTTSHGDSZFFZHARSGYBU0EKG&marketplace=myntra&store=clo%2Fash%2Fank%2Fedy"
    },
    {
      "Platform": "Myntra",
      "breadcrumbs": "Home>Beauty and Grooming>Makeup>Face Makeup>Foundation>Lakmé Foundation>Lakmé 9 to 5 Complexion Care Face Cream - Beige Foundation",
      "title": "Lakmé 9 to 5 Complexion Care Face Cream - Beige Foundation",
      "price": 350,
      "original_price": 360,
      "discount %": 11,
      "currency": "MRP",
      "rating": 4.3,
      "rating_count": 241859,
      "review_count": 21480,
      "offers": "Buy 3, Get 5% Off and Buy 5, Get 10% Off,5% Cashback on myntra Axis Bank Card,Sign up for myntra Pay Later and get myntra Gift Card worth up to ₹500*,Buy this product and get upto ₹250 off on myntra Furniture,No Cost EMI on Bajaj Finserv EMI Card on cart value above ₹2999",
      "description": "<p style=\"text-align: justify;\">\n\tSometimes your skin may need instant makeup when you have a meeting coming up in five minutes. For situations like these, this 9 to 5 Complexion Care Cream – Beige from Lakme will come in handy for you. If you have fair to wheatish complexion, then the beige shade of this cream could be ideal for you.</p>\n<p style=\"text-align: justify;\">\n\t<strong>Instantly Styled Skin</strong><br />\n\tThis cream has the combination of your daily skin cream with just the right touch of makeup, so no matter what the occasion is, it will give you instantly styled skin. Apart from giving you even skin tone, it has SPF 20 that will protect your skin from the sun.</p>\n<p style=\"text-align: justify;\">\n\t<strong>For Moisturized Skin</strong><br />\n\tThis cream is light and gets easily absorbed by your skin. It moisturizes and brightens your skin, while leaving it feeling fresh and natural.</p>",
      "highlights": "It is suitable for skin tone.,Gives a Matte finish look.",
      "services": "",
      "seller": "SURICYBCOMBazaar",
      "seller_rating": 4.3,
      "sizes": "",
      "specifications": "In The Box Sales Package :Foundation,In The Box Pack Of :1,General Brand :Lakmé,General Model Name :9 to 5 Complexion Care Face Cream - Beige,General Shade :Beige,General Quantity :30 g,General Finish :Matte,General Application Area :Face,General Container Type :Tube,General Organic Type :Synthetic,General Ideal For :Women,General Maximum Shelf Life :24 Months,General Color :Beige",
      "images": "http://rukmini1.flixcart.com/image/832/832/khqllzk0/foundation/9/m/u/30-9-to-5-complexion-care-face-cream-beige-lakme-original-imafxzwcqahhn9rc.jpeg,https://www.youtube.com/embed/zuaFEDlflgQ?rel=0,http://rukmini1.flixcart.com/image/832/832/kh80vww0/foundation/9/m/u/30-9-to-5-complexion-care-face-cream-beige-lakme-original-imafxahkgmkmvsmd.jpeg,http://rukmini1.flixcart.com/image/832/832/kh80vww0/foundation/9/m/u/30-9-to-5-complexion-care-face-cream-beige-lakme-original-imafxahknvqqy9p5.jpeg,http://rukmini1.flixcart.com/image/832/832/l2z26q80/shopsy-compact/u/o/i/8-perfect-radiance-test-original-imag55bs4ff52hnn.jpeg,http://rukmini1.flixcart.com/image/832/832/kh80vww0/foundation/9/m/u/30-9-to-5-complexion-care-face-cream-beige-lakme-original-imafxahkzhpn3xuq.jpeg,http://rukmini1.flixcart.com/image/832/832/kh80vww0/foundation/9/f/g/30-9-to-5-complexion-care-cc-cream-lakme-original-imafxahkyzg3bjg7.jpeg",
      "detail_url": "https://www.myntra.com/lakm-9-5-complexion-care-face-cream-beige-foundation/p/itm75cf5003a73ff?pid=FRNEGG5M27YQ99MU&lid=LSTFRNEGG5M27YQ99MUND8HUI&marketplace=myntra&store=g9b%2Fffi"
    },
    {
      "Platform": "Myntra",
      "breadcrumbs": "Home>Footwear>Men's Footwear>Casual Shoes>Warrior By Liberty Casual Shoes>Warrior Original Jungle Boot For Men - Oil Stain & Water Resistant - Extra Cushion Inner Sole - Light Weight Trekking Shoes Boots For Men",
      "title": "Warrior By Liberty Warrior Original Jungle Boot For Men - Oil Stain & Water Resistant - Extra Cushion Inner Sole - Light Weight Trekking Shoes Boots For Men",
      "price": 1500,
      "original_price": 2099,
      "discount %": 5,
      "currency": "FSP",
      "rating": 4.3,
      "rating_count": 3435,
      "review_count": 444,
      "offers": "Get 5% Off on Fashion Product,5% Cashback on myntra Axis Bank Card,Sign up for myntra Pay Later and get myntra Gift Card worth up to ₹500*",
      "description": "",
      "highlights": "",
      "services": "Cash on Delivery,10 Days Return Policy",
      "seller": "Libertyperfume",
      "seller_rating": 4.8,
      "sizes": "5,6,7,7.5,8,8.5,9,9.5,10,11",
      "specifications": "",
      "images": "http://rukmini1.flixcart.com/image/832/832/kh0vonk0-0/shoe/o/i/1/88-46hstg-5-warrior-by-liberty-olive-original-imafx4qrhagaz8xu.jpeg,http://rukmini1.flixcart.com/image/832/832/kcf4lu80-0/shoe/c/7/z/88-46hstg-5-warrior-by-liberty-olive-original-imaftk63yubshhfh.jpeg,http://rukmini1.flixcart.com/image/832/832/kcf4lu80-0/shoe/e/a/q/88-46hstg-5-warrior-by-liberty-olive-original-imaftk62vvgtsjwq.jpeg,http://rukmini1.flixcart.com/image/832/832/kcf4lu80-0/shoe/i/y/n/88-46hstg-5-warrior-by-liberty-olive-original-imaftk62hs5shchn.jpeg,http://rukmini1.flixcart.com/image/832/832/kcf4lu80-0/shoe/r/w/f/88-46hstg-6-warrior-by-liberty-olive-original-imaftk648ymav6bc.jpeg,http://rukmini1.flixcart.com/image/832/832/kh0vonk0-0/shoe/u/t/g/88-46hstg-5-warrior-by-liberty-olive-original-imafx4qrtjtaggds.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/o/3/o/-original-imagg7sygt97fbzb.jpeg",
      "detail_url": "https://www.myntra.com/warrior-liberty-original-jungle-boot-men-oil-stain-water-resistant-extra-cushion-inner-sole-light-weight-trekking-shoes-boots/p/itmfg5zpm9pnyteq?pid=SHOFG4TUZ8SWRRRW&lid=LSTSHOFG4TUZ8SWRRRWWKECGJ&marketplace=myntra&store=osp%2Fcil%2Fe1f"
    },
    {
      "Platform": "Myntra",
      "breadcrumbs": "Home>Furniture>Mattresses>Bed Mattress>PEPS Bed Mattress>PEPS Restonic Sanibel Pillow Top Beige 6 inch King Bonnell Spring Mattress",
      "title": "PEPS Restonic Sanibel Pillow Top Beige 6 inch King Bonnell Spring Mattress",
      "price": 25000,
      "original_price": 43940,
      "discount %": 33,
      "currency": "MRP",
      "rating": 4.1,
      "rating_count": 78,
      "review_count": 20,
      "offers": "10% off on Citi Credit Card Transactions, up to ₹1,500. On orders of ₹5,000 and above,12% off on Citi Credit Card EMI Transactions, up to ₹2,000. On orders of ₹5,000 and above,10% off on Citi Debit Card Transactions, up to ₹1,500. On orders of ₹5,000 and above,Sign up for myntra Pay Later and get myntra Gift Card worth up to ₹500*,Buy this product and get upto ₹500 off on myntra Furniture,NCE EMI on Credit/Debit Card,10% off on ICICI Bank Credit Card EMI Transactions, up to ₹2,000. On orders of ₹5,000 and above,10% off on Kotak Bank Credit Card Transactions, up to ₹1,500. On orders of ₹5,000 and above,12% off on Kotak Bank Credit Card EMI Transactions, up to ₹2,000. On orders of ₹5,000 and above,10% off on Kotak Bank Debit Card Transactions, up to ₹1,500. On orders of ₹5,000 and above,Extra ₹1,000 off on Citi Credit Card (incl. EMI txns) on net cart value of ₹29,999 and above,Extra ₹2,000 off on Citi Credit Card (incl. EMI txns) on net cart value of ₹49,999 and above,5% Cashback on myntra Axis Bank Card",
      "description": "Wake up rejuvenated each mornings with America’s favourite mattress brand. When it comes to mattresses, America trusts Restonic for relaxing sleep every day, not just at home but at some of the world’s best hotels. This internationally patented mattress comes with friction and noise insulation so you can sleep undisturbed and wake up well-rested.",
      "highlights": "Length: 78 inch, Width: 72 inch, Thickness: 6 inch (6 ft 6 in x 6 ft x 6 in),Support Type: Bonnell Spring,Comfort Layer: PU Foam,Mattress Features: Reversible Mattress",
      "services": "Cash on Delivery,10 Days Replacement Policy",
      "seller": "Peps",
      "seller_rating": 4.2,
      "sizes": "6 inch",
      "specifications": "In The Box  :1 Mattress + 2 Pillows,General Brand :PEPS,General Support Layer :Bonnell Spring,General Comfort Layer :PU Foam,General Size :King,General Color :Beige,General Mattress Top :Pillow Top,General Mattress Features :Reversible Mattress,General Comfort Level :Medium Soft,General Upholstery Material :Jacquard,General Removable Cover :No,General Care Instructions :Rotate the mattress every 3 months and flip every 6 months. Always place the mattress on flat surface. Use the side handles to lift the mattress. Make sure the mattress you purchase is equal to your bed size. Exposure to air for some hours regulary will keep the exterior of the mattress dry and hygienic. Do not expose the mattress to direct sunlight. If spillage occurs, treat stain with a wet cloth. Allow to dry thoroughly in the shade before re-using. Good quality, washable mattress protector is a must to keep your mattress fresh and free from stain. Do not iron the mattress or place heat inducing commodities that may lead to fabric melt.,General Reinforced Edges :Yes,General Model Series Name :Restonic Sanibel Pillow Top Beige,Dimensions Thickness :152 mm,Dimensions Width :1828 mm,Dimensions Length :1981 mm,Dimensions Weight :38.188788768 kg,Warranty Warranty Summary :6 years warranty,Warranty Service Type :Customer needs to call or write an email to Customer care, service engineer will visit customer place, inspect and rectify as per the nature of complaint.,Warranty Covered in Warranty :For manufacturing defects with respect to the workmanship and meterial will be Exchanged or reconstructed for no cost for the period of one year from the date of purchase.,Warranty Not Covered in Warranty :For an Operational damage, Accidental, mishandling and poor maintainance, service will be at chargeble.,Warranty Domestic Warranty :6 Year,Disclaimer   :- The color of the product may vary slightly compared to the picture displayed on your screen. This is due to lighting, pixel quality and color settings<br><br> - Please check the product's dimensions to ensure the product will fit in the desired location. Also, check if the product will fit through the entrance(s) and door(s) of the premises<br><br> - Please expect an unevenness of up to 5 mm in the product due to differences in surfaces and floor levels<br><br> - myntra, or the Seller delivering the product, will not take up any type of civil work, such as drilling holes in the wall to mount the product. The product will only be assembled in case carpentry assembly is required<br><br> - In case the product appears to lack shine, wiping the surface with a cloth will help clear the surface of dust particles,Important Note    :This product can only be cancelled within 24 hours of Booking.",
      "images": "http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82jc9pdkbwv.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/m/h/u/single-6-78-36-restonic-sanibel-pillow-top-grey-bonnell-spring-original-imafs82jzghzuktz.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/d/w/e/single-6-78-30-restonic-sanibel-pillow-top-maroon-bonnell-spring-original-imafs82jnhcfgywm.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82jc9pdkbwv.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/n/j/8/double-8-78-42-spine-guard-bonnell-spring-peps-original-imafs82h8dquwwrc.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82jgxzxzerw.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82jd4yzf77q.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82j4qggpxjh.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82js8rnwxsm.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/bed-mattress/z/6/f/-original-imaghpztxzhbg5ze.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/bed-mattress/u/3/6/-original-imaghpztfgmyvvnp.jpeg",
      "detail_url": "https://www.myntra.com/peps-restonic-sanibel-pillow-top-beige-6-inch-king-bonnell-spring-mattress/p/itm27d2773cf1096?pid=BEMF7YA6XFWF9EZ7&lid=LSTBEMF7YA6XFWF9EZ7PC0FGG&marketplace=myntra&store=wwe%2Frg9"
    }
  ]

export const data_amazon = [
    {
      "Platform": "Amazon",
      "breadcrumbs": "Home>Footwear>Men's Footwear>Casual Shoes>getVO Casual Shoes>Chelsea Boots For Men",
      "title": "getVO Chelsea Boots For Men",
      "price": 1200,
      "original_price": 2999,
      "discount %": 61,
      "currency": "MRP",
      "rating": "",
      "rating_count": "",
      "review_count": "",
      "offers": "5% Cashback on amazon Axis Bank Card,Sign up for amazon Pay Later and get amazon Gift Card worth up to ₹500*",
      "description": "",
      "highlights": "",
      "services": "Cash on Delivery,10 Days Return Policy",
      "seller": "GetvoIndia",
      "seller_rating": 4.4,
      "sizes": "6,7,8,9,10",
      "specifications": "",
      "images": "http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/9/m/m/8-sb5003-getvo-tan-original-imagjjfjrkhgmxk6.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/p/z/d/8-sb5003-getvo-tan-original-imagjjfjjja4yupv.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/r/j/e/8-sb5003-getvo-tan-original-imagjjfjxna6vxmb.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/x/c/u/8-sb5003-getvo-tan-original-imagjjfjgnqgshv4.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/y/d/i/8-sb5003-getvo-tan-original-imagjjfjjfmxnfen.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/h/z/0/8-sb5003-getvo-tan-original-imagjjfje2yh4ew7.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/t/w/p/8-sb5003-getvo-tan-original-imagjjfjukj4zhcm.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/j/a/h/8-sb5003-getvo-tan-original-imagjjfjregzphgc.jpeg",
      "detail_url": "https://www.amazon.com/getvo-chelsea-boots-men/p/itm7997ed4701612?pid=SHOGJJFP2UXDBTGP&lid=LSTSHOGJJFP2UXDBTGP57ML4F&marketplace=amazon&store=osp%2Fcil%2Fe1f"
    },
    {
      "Platform": "Amazon",
      "breadcrumbs": "Home>Clothing and Accessories>Topwear>T-shirts>Men's T-shirts>FTX Men's T-shirts>Pack of 4 Men Solid Round Neck Multicolor T-Shirt",
      "title": "FTX Solid Men Round Neck Multicolor T-Shirt",
      "price": 500,
      "original_price": 1499,
      "discount %": 65,
      "currency": "MRP",
      "rating": 4.1,
      "rating_count": 9185,
      "review_count": 769,
      "offers": "Deal Price ₹449,Sign up for amazon Pay Later and get amazon Gift Card worth up to ₹500*,5% Cashback on amazon Axis Bank Card",
      "description": "",
      "highlights": "",
      "services": "Cash on Delivery,10 Days Return Policy",
      "seller": "FORCAS APPARELS",
      "seller_rating": 4.7,
      "sizes": "S,M,L,XL",
      "specifications": "",
      "images": "http://rukmini1.flixcart.com/image/832/832/l2f20sw0/t-shirt/g/4/f/xl-723-5-2-7-8-xl-ftx-original-imagdrzxsvvdjnuk.jpeg,http://rukmini1.flixcart.com/image/832/832/l09w8sw0/t-shirt/o/a/i/m-tst-ab-36-54-ftx-original-imagc36nhgqatpfu.jpeg,http://rukmini1.flixcart.com/image/832/832/l09w8sw0/t-shirt/n/w/b/l-tst-ab-36-54-ftx-original-imagc36nu559bghj.jpeg,http://rukmini1.flixcart.com/image/832/832/l08gsy80/t-shirt/k/5/j/xl-tst-gy-ny-65-68-ftx-original-imagc2ua3nsfc2qh.jpeg,http://rukmini1.flixcart.com/image/832/832/l08gsy80/t-shirt/l/l/c/l-tst-gy-ny-65-68-ftx-original-imagc2uae2fjzrsc.jpeg,http://rukmini1.flixcart.com/image/832/832/l2f20sw0/t-shirt/d/n/a/l-723-2-7-4-8-l-ftx-original-imagdrzutdwnc3ph.jpeg",
      "detail_url": "https://www.amazon.com/ftx-solid-men-round-neck-multicolor-t-shirt/p/itmeafea80350b9b?pid=TSHGDSZFFZHARSGY&lid=LSTTSHGDSZFFZHARSGYBU0EKG&marketplace=amazon&store=clo%2Fash%2Fank%2Fedy"
    },
    {
      "Platform": "Amazon",
      "breadcrumbs": "Home>Beauty and Grooming>Makeup>Face Makeup>Foundation>Lakmé Foundation>Lakmé 9 to 5 Complexion Care Face Cream - Beige Foundation",
      "title": "Lakmé 9 to 5 Complexion Care Face Cream - Beige Foundation",
      "price": 400,
      "original_price": 360,
      "discount %": 11,
      "currency": "MRP",
      "rating": 4.3,
      "rating_count": 241859,
      "review_count": 21480,
      "offers": "Buy 3, Get 5% Off and Buy 5, Get 10% Off,5% Cashback on amazon Axis Bank Card,Sign up for amazon Pay Later and get amazon Gift Card worth up to ₹500*,Buy this product and get upto ₹250 off on amazon Furniture,No Cost EMI on Bajaj Finserv EMI Card on cart value above ₹2999",
      "description": "<p style=\"text-align: justify;\">\n\tSometimes your skin may need instant makeup when you have a meeting coming up in five minutes. For situations like these, this 9 to 5 Complexion Care Cream – Beige from Lakme will come in handy for you. If you have fair to wheatish complexion, then the beige shade of this cream could be ideal for you.</p>\n<p style=\"text-align: justify;\">\n\t<strong>Instantly Styled Skin</strong><br />\n\tThis cream has the combination of your daily skin cream with just the right touch of makeup, so no matter what the occasion is, it will give you instantly styled skin. Apart from giving you even skin tone, it has SPF 20 that will protect your skin from the sun.</p>\n<p style=\"text-align: justify;\">\n\t<strong>For Moisturized Skin</strong><br />\n\tThis cream is light and gets easily absorbed by your skin. It moisturizes and brightens your skin, while leaving it feeling fresh and natural.</p>",
      "highlights": "It is suitable for skin tone.,Gives a Matte finish look.",
      "services": "",
      "seller": "SURICYBCOMBazaar",
      "seller_rating": 4.3,
      "sizes": "",
      "specifications": "In The Box Sales Package :Foundation,In The Box Pack Of :1,General Brand :Lakmé,General Model Name :9 to 5 Complexion Care Face Cream - Beige,General Shade :Beige,General Quantity :30 g,General Finish :Matte,General Application Area :Face,General Container Type :Tube,General Organic Type :Synthetic,General Ideal For :Women,General Maximum Shelf Life :24 Months,General Color :Beige",
      "images": "http://rukmini1.flixcart.com/image/832/832/khqllzk0/foundation/9/m/u/30-9-to-5-complexion-care-face-cream-beige-lakme-original-imafxzwcqahhn9rc.jpeg,https://www.youtube.com/embed/zuaFEDlflgQ?rel=0,http://rukmini1.flixcart.com/image/832/832/kh80vww0/foundation/9/m/u/30-9-to-5-complexion-care-face-cream-beige-lakme-original-imafxahkgmkmvsmd.jpeg,http://rukmini1.flixcart.com/image/832/832/kh80vww0/foundation/9/m/u/30-9-to-5-complexion-care-face-cream-beige-lakme-original-imafxahknvqqy9p5.jpeg,http://rukmini1.flixcart.com/image/832/832/l2z26q80/shopsy-compact/u/o/i/8-perfect-radiance-test-original-imag55bs4ff52hnn.jpeg,http://rukmini1.flixcart.com/image/832/832/kh80vww0/foundation/9/m/u/30-9-to-5-complexion-care-face-cream-beige-lakme-original-imafxahkzhpn3xuq.jpeg,http://rukmini1.flixcart.com/image/832/832/kh80vww0/foundation/9/f/g/30-9-to-5-complexion-care-cc-cream-lakme-original-imafxahkyzg3bjg7.jpeg",
      "detail_url": "https://www.amazon.com/lakm-9-5-complexion-care-face-cream-beige-foundation/p/itm75cf5003a73ff?pid=FRNEGG5M27YQ99MU&lid=LSTFRNEGG5M27YQ99MUND8HUI&marketplace=amazon&store=g9b%2Fffi"
    },
    {
      "Platform": "Amazon",
      "breadcrumbs": "Home>Footwear>Men's Footwear>Casual Shoes>Warrior By Liberty Casual Shoes>Warrior Original Jungle Boot For Men - Oil Stain & Water Resistant - Extra Cushion Inner Sole - Light Weight Trekking Shoes Boots For Men",
      "title": "Warrior By Liberty Warrior Original Jungle Boot For Men - Oil Stain & Water Resistant - Extra Cushion Inner Sole - Light Weight Trekking Shoes Boots For Men",
      "price": 2000,
      "original_price": 2099,
      "discount %": 5,
      "currency": "FSP",
      "rating": 4.3,
      "rating_count": 3435,
      "review_count": 444,
      "offers": "Get 5% Off on Fashion Product,5% Cashback on amazon Axis Bank Card,Sign up for amazon Pay Later and get amazon Gift Card worth up to ₹500*",
      "description": "",
      "highlights": "",
      "services": "Cash on Delivery,10 Days Return Policy",
      "seller": "Libertyperfume",
      "seller_rating": 4.8,
      "sizes": "5,6,7,7.5,8,8.5,9,9.5,10,11",
      "specifications": "",
      "images": "http://rukmini1.flixcart.com/image/832/832/kh0vonk0-0/shoe/o/i/1/88-46hstg-5-warrior-by-liberty-olive-original-imafx4qrhagaz8xu.jpeg,http://rukmini1.flixcart.com/image/832/832/kcf4lu80-0/shoe/c/7/z/88-46hstg-5-warrior-by-liberty-olive-original-imaftk63yubshhfh.jpeg,http://rukmini1.flixcart.com/image/832/832/kcf4lu80-0/shoe/e/a/q/88-46hstg-5-warrior-by-liberty-olive-original-imaftk62vvgtsjwq.jpeg,http://rukmini1.flixcart.com/image/832/832/kcf4lu80-0/shoe/i/y/n/88-46hstg-5-warrior-by-liberty-olive-original-imaftk62hs5shchn.jpeg,http://rukmini1.flixcart.com/image/832/832/kcf4lu80-0/shoe/r/w/f/88-46hstg-6-warrior-by-liberty-olive-original-imaftk648ymav6bc.jpeg,http://rukmini1.flixcart.com/image/832/832/kh0vonk0-0/shoe/u/t/g/88-46hstg-5-warrior-by-liberty-olive-original-imafx4qrtjtaggds.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/o/3/o/-original-imagg7sygt97fbzb.jpeg",
      "detail_url": "https://www.amazon.com/warrior-liberty-original-jungle-boot-men-oil-stain-water-resistant-extra-cushion-inner-sole-light-weight-trekking-shoes-boots/p/itmfg5zpm9pnyteq?pid=SHOFG4TUZ8SWRRRW&lid=LSTSHOFG4TUZ8SWRRRWWKECGJ&marketplace=amazon&store=osp%2Fcil%2Fe1f"
    },
    {
      "Platform": "Amazon",
      "breadcrumbs": "Home>Furniture>Mattresses>Bed Mattress>PEPS Bed Mattress>PEPS Restonic Sanibel Pillow Top Beige 6 inch King Bonnell Spring Mattress",
      "title": "PEPS Restonic Sanibel Pillow Top Beige 6 inch King Bonnell Spring Mattress",
      "price": 30000,
      "original_price": 43940,
      "discount %": 33,
      "currency": "MRP",
      "rating": 4.1,
      "rating_count": 78,
      "review_count": 20,
      "offers": "10% off on Citi Credit Card Transactions, up to ₹1,500. On orders of ₹5,000 and above,12% off on Citi Credit Card EMI Transactions, up to ₹2,000. On orders of ₹5,000 and above,10% off on Citi Debit Card Transactions, up to ₹1,500. On orders of ₹5,000 and above,Sign up for amazon Pay Later and get amazon Gift Card worth up to ₹500*,Buy this product and get upto ₹500 off on amazon Furniture,NCE EMI on Credit/Debit Card,10% off on ICICI Bank Credit Card EMI Transactions, up to ₹2,000. On orders of ₹5,000 and above,10% off on Kotak Bank Credit Card Transactions, up to ₹1,500. On orders of ₹5,000 and above,12% off on Kotak Bank Credit Card EMI Transactions, up to ₹2,000. On orders of ₹5,000 and above,10% off on Kotak Bank Debit Card Transactions, up to ₹1,500. On orders of ₹5,000 and above,Extra ₹1,000 off on Citi Credit Card (incl. EMI txns) on net cart value of ₹29,999 and above,Extra ₹2,000 off on Citi Credit Card (incl. EMI txns) on net cart value of ₹49,999 and above,5% Cashback on amazon Axis Bank Card",
      "description": "Wake up rejuvenated each mornings with America’s favourite mattress brand. When it comes to mattresses, America trusts Restonic for relaxing sleep every day, not just at home but at some of the world’s best hotels. This internationally patented mattress comes with friction and noise insulation so you can sleep undisturbed and wake up well-rested.",
      "highlights": "Length: 78 inch, Width: 72 inch, Thickness: 6 inch (6 ft 6 in x 6 ft x 6 in),Support Type: Bonnell Spring,Comfort Layer: PU Foam,Mattress Features: Reversible Mattress",
      "services": "Cash on Delivery,10 Days Replacement Policy",
      "seller": "Peps",
      "seller_rating": 4.2,
      "sizes": "6 inch",
      "specifications": "In The Box  :1 Mattress + 2 Pillows,General Brand :PEPS,General Support Layer :Bonnell Spring,General Comfort Layer :PU Foam,General Size :King,General Color :Beige,General Mattress Top :Pillow Top,General Mattress Features :Reversible Mattress,General Comfort Level :Medium Soft,General Upholstery Material :Jacquard,General Removable Cover :No,General Care Instructions :Rotate the mattress every 3 months and flip every 6 months. Always place the mattress on flat surface. Use the side handles to lift the mattress. Make sure the mattress you purchase is equal to your bed size. Exposure to air for some hours regulary will keep the exterior of the mattress dry and hygienic. Do not expose the mattress to direct sunlight. If spillage occurs, treat stain with a wet cloth. Allow to dry thoroughly in the shade before re-using. Good quality, washable mattress protector is a must to keep your mattress fresh and free from stain. Do not iron the mattress or place heat inducing commodities that may lead to fabric melt.,General Reinforced Edges :Yes,General Model Series Name :Restonic Sanibel Pillow Top Beige,Dimensions Thickness :152 mm,Dimensions Width :1828 mm,Dimensions Length :1981 mm,Dimensions Weight :38.188788768 kg,Warranty Warranty Summary :6 years warranty,Warranty Service Type :Customer needs to call or write an email to Customer care, service engineer will visit customer place, inspect and rectify as per the nature of complaint.,Warranty Covered in Warranty :For manufacturing defects with respect to the workmanship and meterial will be Exchanged or reconstructed for no cost for the period of one year from the date of purchase.,Warranty Not Covered in Warranty :For an Operational damage, Accidental, mishandling and poor maintainance, service will be at chargeble.,Warranty Domestic Warranty :6 Year,Disclaimer   :- The color of the product may vary slightly compared to the picture displayed on your screen. This is due to lighting, pixel quality and color settings<br><br> - Please check the product's dimensions to ensure the product will fit in the desired location. Also, check if the product will fit through the entrance(s) and door(s) of the premises<br><br> - Please expect an unevenness of up to 5 mm in the product due to differences in surfaces and floor levels<br><br> - amazon, or the Seller delivering the product, will not take up any type of civil work, such as drilling holes in the wall to mount the product. The product will only be assembled in case carpentry assembly is required<br><br> - In case the product appears to lack shine, wiping the surface with a cloth will help clear the surface of dust particles,Important Note    :This product can only be cancelled within 24 hours of Booking.",
      "images": "http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82jc9pdkbwv.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/m/h/u/single-6-78-36-restonic-sanibel-pillow-top-grey-bonnell-spring-original-imafs82jzghzuktz.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/d/w/e/single-6-78-30-restonic-sanibel-pillow-top-maroon-bonnell-spring-original-imafs82jnhcfgywm.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82jc9pdkbwv.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/n/j/8/double-8-78-42-spine-guard-bonnell-spring-peps-original-imafs82h8dquwwrc.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82jgxzxzerw.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82jd4yzf77q.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82j4qggpxjh.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82js8rnwxsm.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/bed-mattress/z/6/f/-original-imaghpztxzhbg5ze.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/bed-mattress/u/3/6/-original-imaghpztfgmyvvnp.jpeg",
      "detail_url": "https://www.amazon.com/peps-restonic-sanibel-pillow-top-beige-6-inch-king-bonnell-spring-mattress/p/itm27d2773cf1096?pid=BEMF7YA6XFWF9EZ7&lid=LSTBEMF7YA6XFWF9EZ7PC0FGG&marketplace=amazon&store=wwe%2Frg9"
    }
  ]

export const data_flipcart = [
    {
      "Platform": "Flipkart",
      "breadcrumbs": "Home>Footwear>Men's Footwear>Casual Shoes>getVO Casual Shoes>Chelsea Boots For Men",
      "title": "getVO Chelsea Boots For Men",
      "price": 1162,
      "original_price": 2999,
      "discount %": 61,
      "currency": "MRP",
      "rating": "",
      "rating_count": "",
      "review_count": "",
      "offers": "5% Cashback on Flipkart Axis Bank Card,Sign up for Flipkart Pay Later and get Flipkart Gift Card worth up to ₹500*",
      "description": "",
      "highlights": "",
      "services": "Cash on Delivery,10 Days Return Policy",
      "seller": "GetvoIndia",
      "seller_rating": 4.4,
      "sizes": "6,7,8,9,10",
      "specifications": "",
      "images": "http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/9/m/m/8-sb5003-getvo-tan-original-imagjjfjrkhgmxk6.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/p/z/d/8-sb5003-getvo-tan-original-imagjjfjjja4yupv.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/r/j/e/8-sb5003-getvo-tan-original-imagjjfjxna6vxmb.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/x/c/u/8-sb5003-getvo-tan-original-imagjjfjgnqgshv4.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/y/d/i/8-sb5003-getvo-tan-original-imagjjfjjfmxnfen.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/h/z/0/8-sb5003-getvo-tan-original-imagjjfje2yh4ew7.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/t/w/p/8-sb5003-getvo-tan-original-imagjjfjukj4zhcm.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/j/a/h/8-sb5003-getvo-tan-original-imagjjfjregzphgc.jpeg",
      "detail_url": "https://www.flipkart.com/getvo-chelsea-boots-men/p/itm7997ed4701612?pid=SHOGJJFP2UXDBTGP&lid=LSTSHOGJJFP2UXDBTGP57ML4F&marketplace=FLIPKART&store=osp%2Fcil%2Fe1f"
    },
    {
      "Platform": "Flipkart",
      "breadcrumbs": "Home>Clothing and Accessories>Topwear>T-shirts>Men's T-shirts>FTX Men's T-shirts>Pack of 4 Men Solid Round Neck Multicolor T-Shirt",
      "title": "FTX Solid Men Round Neck Multicolor T-Shirt",
      "price": 449,
      "original_price": 1499,
      "discount %": 65,
      "currency": "MRP",
      "rating": 4.1,
      "rating_count": 9185,
      "review_count": 769,
      "offers": "Deal Price ₹449,Sign up for Flipkart Pay Later and get Flipkart Gift Card worth up to ₹500*,5% Cashback on Flipkart Axis Bank Card",
      "description": "",
      "highlights": "",
      "services": "Cash on Delivery,10 Days Return Policy",
      "seller": "FORCAS APPARELS",
      "seller_rating": 4.7,
      "sizes": "S,M,L,XL",
      "specifications": "",
      "images": "http://rukmini1.flixcart.com/image/832/832/l2f20sw0/t-shirt/g/4/f/xl-723-5-2-7-8-xl-ftx-original-imagdrzxsvvdjnuk.jpeg,http://rukmini1.flixcart.com/image/832/832/l09w8sw0/t-shirt/o/a/i/m-tst-ab-36-54-ftx-original-imagc36nhgqatpfu.jpeg,http://rukmini1.flixcart.com/image/832/832/l09w8sw0/t-shirt/n/w/b/l-tst-ab-36-54-ftx-original-imagc36nu559bghj.jpeg,http://rukmini1.flixcart.com/image/832/832/l08gsy80/t-shirt/k/5/j/xl-tst-gy-ny-65-68-ftx-original-imagc2ua3nsfc2qh.jpeg,http://rukmini1.flixcart.com/image/832/832/l08gsy80/t-shirt/l/l/c/l-tst-gy-ny-65-68-ftx-original-imagc2uae2fjzrsc.jpeg,http://rukmini1.flixcart.com/image/832/832/l2f20sw0/t-shirt/d/n/a/l-723-2-7-4-8-l-ftx-original-imagdrzutdwnc3ph.jpeg",
      "detail_url": "https://www.flipkart.com/ftx-solid-men-round-neck-multicolor-t-shirt/p/itmeafea80350b9b?pid=TSHGDSZFFZHARSGY&lid=LSTTSHGDSZFFZHARSGYBU0EKG&marketplace=FLIPKART&store=clo%2Fash%2Fank%2Fedy"
    },
    {
      "Platform": "Flipkart",
      "breadcrumbs": "Home>Beauty and Grooming>Makeup>Face Makeup>Foundation>Lakmé Foundation>Lakmé 9 to 5 Complexion Care Face Cream - Beige Foundation",
      "title": "Lakmé 9 to 5 Complexion Care Face Cream - Beige Foundation",
      "price": 320,
      "original_price": 360,
      "discount %": 11,
      "currency": "MRP",
      "rating": 4.3,
      "rating_count": 241859,
      "review_count": 21480,
      "offers": "Buy 3, Get 5% Off and Buy 5, Get 10% Off,5% Cashback on Flipkart Axis Bank Card,Sign up for Flipkart Pay Later and get Flipkart Gift Card worth up to ₹500*,Buy this product and get upto ₹250 off on Flipkart Furniture,No Cost EMI on Bajaj Finserv EMI Card on cart value above ₹2999",
      "description": "<p style=\"text-align: justify;\">\n\tSometimes your skin may need instant makeup when you have a meeting coming up in five minutes. For situations like these, this 9 to 5 Complexion Care Cream – Beige from Lakme will come in handy for you. If you have fair to wheatish complexion, then the beige shade of this cream could be ideal for you.</p>\n<p style=\"text-align: justify;\">\n\t<strong>Instantly Styled Skin</strong><br />\n\tThis cream has the combination of your daily skin cream with just the right touch of makeup, so no matter what the occasion is, it will give you instantly styled skin. Apart from giving you even skin tone, it has SPF 20 that will protect your skin from the sun.</p>\n<p style=\"text-align: justify;\">\n\t<strong>For Moisturized Skin</strong><br />\n\tThis cream is light and gets easily absorbed by your skin. It moisturizes and brightens your skin, while leaving it feeling fresh and natural.</p>",
      "highlights": "It is suitable for skin tone.,Gives a Matte finish look.",
      "services": "",
      "seller": "SURICYBCOMBazaar",
      "seller_rating": 4.3,
      "sizes": "",
      "specifications": "In The Box Sales Package :Foundation,In The Box Pack Of :1,General Brand :Lakmé,General Model Name :9 to 5 Complexion Care Face Cream - Beige,General Shade :Beige,General Quantity :30 g,General Finish :Matte,General Application Area :Face,General Container Type :Tube,General Organic Type :Synthetic,General Ideal For :Women,General Maximum Shelf Life :24 Months,General Color :Beige",
      "images": "http://rukmini1.flixcart.com/image/832/832/khqllzk0/foundation/9/m/u/30-9-to-5-complexion-care-face-cream-beige-lakme-original-imafxzwcqahhn9rc.jpeg,https://www.youtube.com/embed/zuaFEDlflgQ?rel=0,http://rukmini1.flixcart.com/image/832/832/kh80vww0/foundation/9/m/u/30-9-to-5-complexion-care-face-cream-beige-lakme-original-imafxahkgmkmvsmd.jpeg,http://rukmini1.flixcart.com/image/832/832/kh80vww0/foundation/9/m/u/30-9-to-5-complexion-care-face-cream-beige-lakme-original-imafxahknvqqy9p5.jpeg,http://rukmini1.flixcart.com/image/832/832/l2z26q80/shopsy-compact/u/o/i/8-perfect-radiance-test-original-imag55bs4ff52hnn.jpeg,http://rukmini1.flixcart.com/image/832/832/kh80vww0/foundation/9/m/u/30-9-to-5-complexion-care-face-cream-beige-lakme-original-imafxahkzhpn3xuq.jpeg,http://rukmini1.flixcart.com/image/832/832/kh80vww0/foundation/9/f/g/30-9-to-5-complexion-care-cc-cream-lakme-original-imafxahkyzg3bjg7.jpeg",
      "detail_url": "https://www.flipkart.com/lakm-9-5-complexion-care-face-cream-beige-foundation/p/itm75cf5003a73ff?pid=FRNEGG5M27YQ99MU&lid=LSTFRNEGG5M27YQ99MUND8HUI&marketplace=FLIPKART&store=g9b%2Fffi"
    },
    {
      "Platform": "Flipkart",
      "breadcrumbs": "Home>Footwear>Men's Footwear>Casual Shoes>Warrior By Liberty Casual Shoes>Warrior Original Jungle Boot For Men - Oil Stain & Water Resistant - Extra Cushion Inner Sole - Light Weight Trekking Shoes Boots For Men",
      "title": "Warrior By Liberty Warrior Original Jungle Boot For Men - Oil Stain & Water Resistant - Extra Cushion Inner Sole - Light Weight Trekking Shoes Boots For Men",
      "price": 1994,
      "original_price": 2099,
      "discount %": 5,
      "currency": "FSP",
      "rating": 4.3,
      "rating_count": 3435,
      "review_count": 444,
      "offers": "Get 5% Off on Fashion Product,5% Cashback on Flipkart Axis Bank Card,Sign up for Flipkart Pay Later and get Flipkart Gift Card worth up to ₹500*",
      "description": "",
      "highlights": "",
      "services": "Cash on Delivery,10 Days Return Policy",
      "seller": "Libertyperfume",
      "seller_rating": 4.8,
      "sizes": "5,6,7,7.5,8,8.5,9,9.5,10,11",
      "specifications": "",
      "images": "http://rukmini1.flixcart.com/image/832/832/kh0vonk0-0/shoe/o/i/1/88-46hstg-5-warrior-by-liberty-olive-original-imafx4qrhagaz8xu.jpeg,http://rukmini1.flixcart.com/image/832/832/kcf4lu80-0/shoe/c/7/z/88-46hstg-5-warrior-by-liberty-olive-original-imaftk63yubshhfh.jpeg,http://rukmini1.flixcart.com/image/832/832/kcf4lu80-0/shoe/e/a/q/88-46hstg-5-warrior-by-liberty-olive-original-imaftk62vvgtsjwq.jpeg,http://rukmini1.flixcart.com/image/832/832/kcf4lu80-0/shoe/i/y/n/88-46hstg-5-warrior-by-liberty-olive-original-imaftk62hs5shchn.jpeg,http://rukmini1.flixcart.com/image/832/832/kcf4lu80-0/shoe/r/w/f/88-46hstg-6-warrior-by-liberty-olive-original-imaftk648ymav6bc.jpeg,http://rukmini1.flixcart.com/image/832/832/kh0vonk0-0/shoe/u/t/g/88-46hstg-5-warrior-by-liberty-olive-original-imafx4qrtjtaggds.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/shoe/o/3/o/-original-imagg7sygt97fbzb.jpeg",
      "detail_url": "https://www.flipkart.com/warrior-liberty-original-jungle-boot-men-oil-stain-water-resistant-extra-cushion-inner-sole-light-weight-trekking-shoes-boots/p/itmfg5zpm9pnyteq?pid=SHOFG4TUZ8SWRRRW&lid=LSTSHOFG4TUZ8SWRRRWWKECGJ&marketplace=FLIPKART&store=osp%2Fcil%2Fe1f"
    },
    {
      "Platform": "Flipkart",
      "breadcrumbs": "Home>Furniture>Mattresses>Bed Mattress>PEPS Bed Mattress>PEPS Restonic Sanibel Pillow Top Beige 6 inch King Bonnell Spring Mattress",
      "title": "PEPS Restonic Sanibel Pillow Top Beige 6 inch King Bonnell Spring Mattress",
      "price": 29152,
      "original_price": 43940,
      "discount %": 33,
      "currency": "MRP",
      "rating": 4.1,
      "rating_count": 78,
      "review_count": 20,
      "offers": "10% off on Citi Credit Card Transactions, up to ₹1,500. On orders of ₹5,000 and above,12% off on Citi Credit Card EMI Transactions, up to ₹2,000. On orders of ₹5,000 and above,10% off on Citi Debit Card Transactions, up to ₹1,500. On orders of ₹5,000 and above,Sign up for Flipkart Pay Later and get Flipkart Gift Card worth up to ₹500*,Buy this product and get upto ₹500 off on Flipkart Furniture,NCE EMI on Credit/Debit Card,10% off on ICICI Bank Credit Card EMI Transactions, up to ₹2,000. On orders of ₹5,000 and above,10% off on Kotak Bank Credit Card Transactions, up to ₹1,500. On orders of ₹5,000 and above,12% off on Kotak Bank Credit Card EMI Transactions, up to ₹2,000. On orders of ₹5,000 and above,10% off on Kotak Bank Debit Card Transactions, up to ₹1,500. On orders of ₹5,000 and above,Extra ₹1,000 off on Citi Credit Card (incl. EMI txns) on net cart value of ₹29,999 and above,Extra ₹2,000 off on Citi Credit Card (incl. EMI txns) on net cart value of ₹49,999 and above,5% Cashback on Flipkart Axis Bank Card",
      "description": "Wake up rejuvenated each mornings with America’s favourite mattress brand. When it comes to mattresses, America trusts Restonic for relaxing sleep every day, not just at home but at some of the world’s best hotels. This internationally patented mattress comes with friction and noise insulation so you can sleep undisturbed and wake up well-rested.",
      "highlights": "Length: 78 inch, Width: 72 inch, Thickness: 6 inch (6 ft 6 in x 6 ft x 6 in),Support Type: Bonnell Spring,Comfort Layer: PU Foam,Mattress Features: Reversible Mattress",
      "services": "Cash on Delivery,10 Days Replacement Policy",
      "seller": "Peps",
      "seller_rating": 4.2,
      "sizes": "6 inch",
      "specifications": "In The Box  :1 Mattress + 2 Pillows,General Brand :PEPS,General Support Layer :Bonnell Spring,General Comfort Layer :PU Foam,General Size :King,General Color :Beige,General Mattress Top :Pillow Top,General Mattress Features :Reversible Mattress,General Comfort Level :Medium Soft,General Upholstery Material :Jacquard,General Removable Cover :No,General Care Instructions :Rotate the mattress every 3 months and flip every 6 months. Always place the mattress on flat surface. Use the side handles to lift the mattress. Make sure the mattress you purchase is equal to your bed size. Exposure to air for some hours regulary will keep the exterior of the mattress dry and hygienic. Do not expose the mattress to direct sunlight. If spillage occurs, treat stain with a wet cloth. Allow to dry thoroughly in the shade before re-using. Good quality, washable mattress protector is a must to keep your mattress fresh and free from stain. Do not iron the mattress or place heat inducing commodities that may lead to fabric melt.,General Reinforced Edges :Yes,General Model Series Name :Restonic Sanibel Pillow Top Beige,Dimensions Thickness :152 mm,Dimensions Width :1828 mm,Dimensions Length :1981 mm,Dimensions Weight :38.188788768 kg,Warranty Warranty Summary :6 years warranty,Warranty Service Type :Customer needs to call or write an email to Customer care, service engineer will visit customer place, inspect and rectify as per the nature of complaint.,Warranty Covered in Warranty :For manufacturing defects with respect to the workmanship and meterial will be Exchanged or reconstructed for no cost for the period of one year from the date of purchase.,Warranty Not Covered in Warranty :For an Operational damage, Accidental, mishandling and poor maintainance, service will be at chargeble.,Warranty Domestic Warranty :6 Year,Disclaimer   :- The color of the product may vary slightly compared to the picture displayed on your screen. This is due to lighting, pixel quality and color settings<br><br> - Please check the product's dimensions to ensure the product will fit in the desired location. Also, check if the product will fit through the entrance(s) and door(s) of the premises<br><br> - Please expect an unevenness of up to 5 mm in the product due to differences in surfaces and floor levels<br><br> - Flipkart, or the Seller delivering the product, will not take up any type of civil work, such as drilling holes in the wall to mount the product. The product will only be assembled in case carpentry assembly is required<br><br> - In case the product appears to lack shine, wiping the surface with a cloth will help clear the surface of dust particles,Important Note    :This product can only be cancelled within 24 hours of Booking.",
      "images": "http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82jc9pdkbwv.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/m/h/u/single-6-78-36-restonic-sanibel-pillow-top-grey-bonnell-spring-original-imafs82jzghzuktz.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/d/w/e/single-6-78-30-restonic-sanibel-pillow-top-maroon-bonnell-spring-original-imafs82jnhcfgywm.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82jc9pdkbwv.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/n/j/8/double-8-78-42-spine-guard-bonnell-spring-peps-original-imafs82h8dquwwrc.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82jgxzxzerw.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82jd4yzf77q.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82j4qggpxjh.jpeg,http://rukmini1.flixcart.com/image/832/832/kapoo7k0/bed-mattress/q/f/9/double-6-72-48-restonic-sanibel-pillow-top-beige-bonnell-spring-original-imafs82js8rnwxsm.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/bed-mattress/z/6/f/-original-imaghpztxzhbg5ze.jpeg,http://rukmini1.flixcart.com/image/832/832/xif0q/bed-mattress/u/3/6/-original-imaghpztfgmyvvnp.jpeg",
      "detail_url": "https://www.flipkart.com/peps-restonic-sanibel-pillow-top-beige-6-inch-king-bonnell-spring-mattress/p/itm27d2773cf1096?pid=BEMF7YA6XFWF9EZ7&lid=LSTBEMF7YA6XFWF9EZ7PC0FGG&marketplace=FLIPKART&store=wwe%2Frg9"
    }
  ]